server {
    server_name taimur.sh www.taimur.sh;

    root /home/taimur/dev/sketchpad/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/taimur.sh/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/taimur.sh/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = taimur.sh) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name taimur.sh www.taimur.sh;
    return 404; # managed by Certbot


}